//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFootball_PES2021_Stadium_ID_Changer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eFootball_PES2021_Stadium_ID_Changer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CityHash {
            get {
                object obj = ResourceManager.GetObject("CityHash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/tpp/chara/prs/Scenes/prs0_main0_def.fmdl
        ////Assets/tpp/chara/prs/Scenes/prs0_main0_def.frdv
        ////Assets/tpp/chara/psy/Pictures/psy0_main0_def_bsm.1.ftexs
        ////Assets/tpp/chara/psy/Pictures/psy0_main0_def_bsm.2.ftexs
        ////Assets/tpp/chara/psy/Pictures/psy0_main0_def_bsm.3.ftexs
        ////Assets/tpp/chara/psy/Pictures/psy0_main0_def_bsm.ftex
        ////Assets/tpp/chara/psy/Scenes/psy0_main0_def.fmdl
        ////Assets/tpp/chara/psy/Scenes/psy0_main0_def.frdv
        ////Assets/tpp/chara/rai/Fox_files/rai0_main0_asr.sim
        ////Assets/tpp/chara/rai/Fox_f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fox_dictionary {
            get {
                return ResourceManager.GetString("fox_dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FoxTool {
            get {
                object obj = ResourceManager.GetObject("FoxTool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GzsTool {
            get {
                object obj = ResourceManager.GetObject("GzsTool", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
